spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/fitmanager_db
spring.datasource.username=postgres
spring.datasource.password=Tello1435
spring.jpa.hibernate.ddl-auto=update
