spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/fitmanager_db
spring.datasource.username=postgres
spring.datasource.password=Tello1435
spring.jpa.hibernate.ddl-auto=update
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.properties.hibernate.jdbc.time_zone=America/Argentina/Buenos_Aires
